package controller

import (
	"github.com/gin-gonic/gin"

	"github.com/ricky97gr/chprobe/chprobe_server/response"
	"github.com/ricky97gr/chprobe/chprobe_server/utils"
)

// 生成安装命令
func GenerateInstallCommand(c *gin.Context) {
	serverAddr := c.Request.Host
	installCommand := generateCommand(serverAddr)
	response.Success(c, gin.H{
		"command": installCommand,
	}, 1)
}

// 下载安装包
func DownloadInstaller(c *gin.Context) {
	filename := c.Param("filename")

	if filename == "chprobe_installer.sh" {
		// 生成安装脚本
		serverAddr := c.Request.Host
		installScript := generateInstallScript(serverAddr)
		c.Header("Content-Disposition", "attachment; filename="+filename)
		c.Header("Content-Type", "application/octet-stream")
		c.String(200, installScript)
		return
	}

	if filename == "chprobe_client" {
		// 生成客户端安装包
		serverAddr := c.Request.Host
		installer, err := utils.GenerateInstaller(serverAddr)
		if err != nil {
			response.Failed(c, response.ErrDB, "Failed to generate installer")
			return
		}
		c.Header("Content-Disposition", "attachment; filename="+filename+".tar.gz")
		c.Header("Content-Type", "application/octet-stream")
		c.Data(200, "application/octet-stream", installer)
		return
	}

	if filename == "config.yaml" {
		// 生成配置文件
		serverAddr := c.Request.Host
		configContent := generateConfigFile(serverAddr)
		c.Header("Content-Disposition", "attachment; filename="+filename)
		c.Header("Content-Type", "application/octet-stream")
		c.String(200, configContent)
		return
	}

	response.Failed(c, response.ErrRecordNotFound, "File not found")
}

// 生成安装脚本
func generateInstallScript(serverAddr string) string {
	return `#!/bin/bash

set -e

echo "正在安装 Chprobe 客户端..."

# 下载安装包压缩文件
wget -O chprobe_client.tar.gz http://` + serverAddr + `/api/download/chprobe_client

# 解压到当前目录
echo "正在解压安装包..."
tar -xzf chprobe_client.tar.gz

# 进入解压后的目录
cd chprobe_client

# 赋予执行权限
chmod +x chprobe_client

# 运行客户端
echo "正在启动 Chprobe 客户端..."
./chprobe_client &

echo "安装完成！"
echo "Chprobe 客户端已成功安装并启动。"
echo "安装位置: $(pwd)"
echo "配置文件位置: $(pwd)/config.yaml"
echo "运行状态: ps aux | grep chprobe_client"
`
}

// 生成配置文件
func generateConfigFile(serverAddr string) string {
	// 从serverAddr中提取IP
	ip := serverAddr
	// 简单处理，假设serverAddr格式为 ip:port
	// 这里可以添加更复杂的解析逻辑

	return `# Server configuration
serverIP: "` + ip + `"
serverPort: "32000"

# Client UUID (auto-generated by server)
uuid: ""
`
}

// 生成安装命令
func generateCommand(serverAddr string) string {
	// 生成安装命令，包含服务器地址
	command := `#!/bin/bash

# Chprobe 安装脚本

set -e

echo "正在安装 Chprobe 客户端..."

# 下载安装包
wget -O chprobe_installer.sh http://` + serverAddr + `/api/download/chprobe_installer.sh

# 执行安装脚本
chmod +x chprobe_installer.sh
./chprobe_installer.sh "` + serverAddr + `"

echo "安装完成！"
`
	return command
}
