package utils

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"os"
	"path/filepath"
)

// 生成安装包
func GenerateInstaller(serverAddr string) ([]byte, error) {
	// 创建一个内存缓冲区来存储tar.gz文件
	buf := new(bytes.Buffer)
	gz := gzip.NewWriter(buf)
	tw := tar.NewWriter(gz)

	// 添加配置文件模板
	configContent := generateConfigTemplate(serverAddr)
	err := addFileToTar(tw, "chprobe_client/config.yaml", configContent)
	if err != nil {
		return nil, err
	}

	// 添加客户端可执行文件（模拟）
	clientContent := generateMockClient()
	err = addFileToTar(tw, "chprobe_client/chprobe_client", clientContent)
	if err != nil {
		return nil, err
	}

	// 关闭tar和gzip写入器
	err = tw.Close()
	if err != nil {
		return nil, err
	}
	err = gz.Close()
	if err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

// 生成模拟客户端可执行文件
func generateMockClient() string {
	return `#!/bin/bash

# 模拟 Chprobe 客户端

echo "Chprobe client started"
echo "Connecting to server..."
echo "Registration completed"
echo "Heartbeat started"

# 无限循环
while true; do
	sleep 60
echo "Sending heartbeat..."
done
`
}

// 生成安装脚本
func generateInstallScript(serverAddr string) string {
	return fmt.Sprintf(`#!/bin/bash

set -e

echo "正在安装 Chprobe 客户端..."

# 创建安装目录
INSTALL_DIR="/opt/chprobe"
mkdir -p $INSTALL_DIR

# 复制配置文件
cp config.yaml $INSTALL_DIR/

# 下载客户端二进制文件
# 注意：实际生产环境中，应该从构建服务器或CDN下载
# 这里简化处理，假设二进制文件已经存在
# wget -O $INSTALL_DIR/chprobe_client http://%s/api/download/chprobe_client

# 模拟创建客户端二进制文件
echo "模拟创建客户端二进制文件..."
echo "#!/bin/bash
echo \"Chprobe client started\"" > $INSTALL_DIR/chprobe_client
chmod +x $INSTALL_DIR/chprobe_client

# 创建系统服务文件
SERVICE_FILE="/etc/systemd/system/chprobe.service"
echo "[Unit]
Description=Chprobe Client
After=network.target

[Service]
ExecStart=$INSTALL_DIR/chprobe_client
WorkingDirectory=$INSTALL_DIR
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target" > $SERVICE_FILE

# 启用并启动服务
systemctl daemon-reload
systemctl enable chprobe
systemctl start chprobe

echo "安装完成！"
echo "Chprobe 客户端已成功安装并启动。"
echo "配置文件位置: $INSTALL_DIR/config.yaml"
echo "服务状态: systemctl status chprobe"
`, serverAddr)
}

// 生成配置文件模板
func generateConfigTemplate(serverAddr string) string {
	// 从serverAddr中提取IP和端口
	ip := "127.0.0.1"
	port := "32000"

	// 简单处理，假设serverAddr格式为 ip:port
	if len(serverAddr) > 0 {
		ip = serverAddr
		// 这里可以添加更复杂的解析逻辑
	}

	return fmt.Sprintf(`# Server configuration
serverIP: "%s"
serverPort: "%s"

# Client UUID (auto-generated by server)
uuid: ""
`, ip, port)
}

// 添加文件到tar包
func addFileToTar(tw *tar.Writer, filename string, content string) error {
	hdr := &tar.Header{
		Name: filename,
		Mode: 0755,
		Size: int64(len(content)),
	}
	err := tw.WriteHeader(hdr)
	if err != nil {
		return err
	}
	_, err = io.WriteString(tw, content)
	return err
}

// 保存安装包到文件
func SaveInstaller(data []byte, outputPath string) error {
	err := os.MkdirAll(filepath.Dir(outputPath), 0755)
	if err != nil {
		return err
	}

	err = os.WriteFile(outputPath, data, 0644)
	if err != nil {
		return err
	}

	return nil
}
