// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.12.4
// source: reporter.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Reporter_ReportToServer_FullMethodName = "/reporter.Reporter/ReportToServer"
)

// ReporterClient is the client API for Reporter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReporterClient interface {
	ReportToServer(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MessageInfo, ServerMessage], error)
}

type reporterClient struct {
	cc grpc.ClientConnInterface
}

func NewReporterClient(cc grpc.ClientConnInterface) ReporterClient {
	return &reporterClient{cc}
}

func (c *reporterClient) ReportToServer(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MessageInfo, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Reporter_ServiceDesc.Streams[0], Reporter_ReportToServer_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MessageInfo, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Reporter_ReportToServerClient = grpc.BidiStreamingClient[MessageInfo, ServerMessage]

// ReporterServer is the server API for Reporter service.
// All implementations must embed UnimplementedReporterServer
// for forward compatibility.
type ReporterServer interface {
	ReportToServer(grpc.BidiStreamingServer[MessageInfo, ServerMessage]) error
	mustEmbedUnimplementedReporterServer()
}

// UnimplementedReporterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReporterServer struct{}

func (UnimplementedReporterServer) ReportToServer(grpc.BidiStreamingServer[MessageInfo, ServerMessage]) error {
	return status.Error(codes.Unimplemented, "method ReportToServer not implemented")
}
func (UnimplementedReporterServer) mustEmbedUnimplementedReporterServer() {}
func (UnimplementedReporterServer) testEmbeddedByValue()                  {}

// UnsafeReporterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReporterServer will
// result in compilation errors.
type UnsafeReporterServer interface {
	mustEmbedUnimplementedReporterServer()
}

func RegisterReporterServer(s grpc.ServiceRegistrar, srv ReporterServer) {
	// If the following call panics, it indicates UnimplementedReporterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Reporter_ServiceDesc, srv)
}

func _Reporter_ReportToServer_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ReporterServer).ReportToServer(&grpc.GenericServerStream[MessageInfo, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Reporter_ReportToServerServer = grpc.BidiStreamingServer[MessageInfo, ServerMessage]

// Reporter_ServiceDesc is the grpc.ServiceDesc for Reporter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Reporter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "reporter.Reporter",
	HandlerType: (*ReporterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReportToServer",
			Handler:       _Reporter_ReportToServer_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "reporter.proto",
}
