// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: reporter.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Client        string                 `protobuf:"bytes,1,opt,name=Client,proto3" json:"Client,omitempty"`
	MessageType   int32                  `protobuf:"varint,2,opt,name=MessageType,proto3" json:"MessageType,omitempty"`
	ReportTime    int64                  `protobuf:"varint,3,opt,name=ReportTime,proto3" json:"ReportTime,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageInfo) Reset() {
	*x = MessageInfo{}
	mi := &file_reporter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageInfo) ProtoMessage() {}

func (x *MessageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_reporter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageInfo.ProtoReflect.Descriptor instead.
func (*MessageInfo) Descriptor() ([]byte, []int) {
	return file_reporter_proto_rawDescGZIP(), []int{0}
}

func (x *MessageInfo) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *MessageInfo) GetMessageType() int32 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

func (x *MessageInfo) GetReportTime() int64 {
	if x != nil {
		return x.ReportTime
	}
	return 0
}

func (x *MessageInfo) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	Result        string                 `protobuf:"bytes,2,opt,name=Result,proto3" json:"Result,omitempty"`
	DataLength    int32                  `protobuf:"varint,3,opt,name=DataLength,proto3" json:"DataLength,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_reporter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_reporter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_reporter_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Response) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *Response) GetDataLength() int32 {
	if x != nil {
		return x.DataLength
	}
	return 0
}

var File_reporter_proto protoreflect.FileDescriptor

const file_reporter_proto_rawDesc = "" +
	"\n" +
	"\x0ereporter.proto\x12\breporter\"{\n" +
	"\vMessageInfo\x12\x16\n" +
	"\x06Client\x18\x01 \x01(\tR\x06Client\x12 \n" +
	"\vMessageType\x18\x02 \x01(\x05R\vMessageType\x12\x1e\n" +
	"\n" +
	"ReportTime\x18\x03 \x01(\x03R\n" +
	"ReportTime\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"\\\n" +
	"\bResponse\x12\x18\n" +
	"\aSuccess\x18\x01 \x01(\bR\aSuccess\x12\x16\n" +
	"\x06Result\x18\x02 \x01(\tR\x06Result\x12\x1e\n" +
	"\n" +
	"DataLength\x18\x03 \x01(\x05R\n" +
	"DataLength2I\n" +
	"\bReporter\x12=\n" +
	"\x0eReportToServer\x12\x15.reporter.MessageInfo\x1a\x12.reporter.Response\"\x00B\n" +
	"Z\b./;protob\x06proto3"

var (
	file_reporter_proto_rawDescOnce sync.Once
	file_reporter_proto_rawDescData []byte
)

func file_reporter_proto_rawDescGZIP() []byte {
	file_reporter_proto_rawDescOnce.Do(func() {
		file_reporter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reporter_proto_rawDesc), len(file_reporter_proto_rawDesc)))
	})
	return file_reporter_proto_rawDescData
}

var file_reporter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_reporter_proto_goTypes = []any{
	(*MessageInfo)(nil), // 0: reporter.MessageInfo
	(*Response)(nil),    // 1: reporter.Response
}
var file_reporter_proto_depIdxs = []int32{
	0, // 0: reporter.Reporter.ReportToServer:input_type -> reporter.MessageInfo
	1, // 1: reporter.Reporter.ReportToServer:output_type -> reporter.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_reporter_proto_init() }
func file_reporter_proto_init() {
	if File_reporter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reporter_proto_rawDesc), len(file_reporter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reporter_proto_goTypes,
		DependencyIndexes: file_reporter_proto_depIdxs,
		MessageInfos:      file_reporter_proto_msgTypes,
	}.Build()
	File_reporter_proto = out.File
	file_reporter_proto_goTypes = nil
	file_reporter_proto_depIdxs = nil
}
